// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCm6qlfTr_Ap4ABfSGpXZPJDcF9HvF52U',
    appId: '1:100179654850:web:5c029aafb4a859870be35b',
    messagingSenderId: '100179654850',
    projectId: 'aditus-v1',
    authDomain: 'aditus-v1.firebaseapp.com',
    storageBucket: 'aditus-v1.appspot.com',
    measurementId: 'G-L6J12GP0G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC34fjx1ZqyWDzsjmNbu5SIGs_PU9iBUzg',
    appId: '1:100179654850:android:1ce3ae2de0fd7bbc0be35b',
    messagingSenderId: '100179654850',
    projectId: 'aditus-v1',
    storageBucket: 'aditus-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3WgSwbima2rXKUf9q5VXAR0XSWSTwkYY',
    appId: '1:100179654850:ios:c7fda6c5b043bbf70be35b',
    messagingSenderId: '100179654850',
    projectId: 'aditus-v1',
    storageBucket: 'aditus-v1.appspot.com',
    iosBundleId: 'com.example.aditusV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3WgSwbima2rXKUf9q5VXAR0XSWSTwkYY',
    appId: '1:100179654850:ios:e30e30a26a76ae270be35b',
    messagingSenderId: '100179654850',
    projectId: 'aditus-v1',
    storageBucket: 'aditus-v1.appspot.com',
    iosBundleId: 'com.example.aditusV1.RunnerTests',
  );
}
